# Generated by Django 3.1.5 on 2021-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211219_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('PLACED', 'PLACED'), ('PROCESSED', 'PROCESSED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=20),
        ),
    ]
